workspace = { members = ["client", "proxy", "server"] }
# [build]
# rustflags = ["--cfg", "tokio_unstable"]

[package]
name = "tls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
